modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="letfishlove"
version="${file.jarVersion}" #mandatory
displayName="Let Fish Love" #mandatory
credits="Assets and Idea by toomanykitkats" #optional
authors="Uraneptus" #optional
description='''
'''
[[dependencies.letfishlove]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.letfishlove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
